-- DEMANDA

-- Pronóstico oficial de demanda (definitivo)

CREATE TABLE xm.PRONOSTICO_OFICIAL_DEMANDA_DEFINITIVO (
    FECHA DATE NOT NULL,
    VALUES_CODE VARCHAR(7) NOT NULL,
    VALUES_HOUR01 NUMERIC NOT NULL,
    VALUES_HOUR02 NUMERIC NOT NULL,
    VALUES_HOUR03 NUMERIC NOT NULL,
    VALUES_HOUR04 NUMERIC NOT NULL,
    VALUES_HOUR05 NUMERIC NOT NULL,
    VALUES_HOUR06 NUMERIC NOT NULL,
    VALUES_HOUR07 NUMERIC NOT NULL,
    VALUES_HOUR08 NUMERIC NOT NULL,
    VALUES_HOUR09 NUMERIC NOT NULL,
    VALUES_HOUR10 NUMERIC NOT NULL,
    VALUES_HOUR11 NUMERIC NOT NULL,
    VALUES_HOUR12 NUMERIC NOT NULL,
    VALUES_HOUR13 NUMERIC NOT NULL,
    VALUES_HOUR14 NUMERIC NOT NULL,
    VALUES_HOUR15 NUMERIC NOT NULL,
    VALUES_HOUR16 NUMERIC NOT NULL,
    VALUES_HOUR17 NUMERIC NOT NULL,
    VALUES_HOUR18 NUMERIC NOT NULL,
    VALUES_HOUR19 NUMERIC NOT NULL,
    VALUES_HOUR20 NUMERIC NOT NULL,
    VALUES_HOUR21 NUMERIC NOT NULL,
    VALUES_HOUR22 NUMERIC NOT NULL,
    VALUES_HOUR23 NUMERIC NOT NULL,
    VALUES_HOUR24 NUMERIC NOT NULL
);

-- Demanda comercial Sistema

CREATE TABLE xm.DEMANDA_COMERCIAL_SISTEMA (
    FECHA DATE NOT NULL,
    VALUES_CODE VARCHAR(7) NOT NULL,
    VALUES_HOUR01 NUMERIC NOT NULL,
    VALUES_HOUR02 NUMERIC NOT NULL,
    VALUES_HOUR03 NUMERIC NOT NULL,
    VALUES_HOUR04 NUMERIC NOT NULL,
    VALUES_HOUR05 NUMERIC NOT NULL,
    VALUES_HOUR06 NUMERIC NOT NULL,
    VALUES_HOUR07 NUMERIC NOT NULL,
    VALUES_HOUR08 NUMERIC NOT NULL,
    VALUES_HOUR09 NUMERIC NOT NULL,
    VALUES_HOUR10 NUMERIC NOT NULL,
    VALUES_HOUR11 NUMERIC NOT NULL,
    VALUES_HOUR12 NUMERIC NOT NULL,
    VALUES_HOUR13 NUMERIC NOT NULL,
    VALUES_HOUR14 NUMERIC NOT NULL,
    VALUES_HOUR15 NUMERIC NOT NULL,
    VALUES_HOUR16 NUMERIC NOT NULL,
    VALUES_HOUR17 NUMERIC NOT NULL,
    VALUES_HOUR18 NUMERIC NOT NULL,
    VALUES_HOUR19 NUMERIC NOT NULL,
    VALUES_HOUR20 NUMERIC NOT NULL,
    VALUES_HOUR21 NUMERIC NOT NULL,
    VALUES_HOUR22 NUMERIC NOT NULL,
    VALUES_HOUR23 NUMERIC NOT NULL,
    VALUES_HOUR24 NUMERIC NOT NULL
);

-- TRANSACCIONES Y PRECIOS

-- Precio de oferta del despacho

CREATE TABLE xm.PRECIO_OFERTA_DESPACHO (
    FECHA DATE NOT NULL,
    VALUES_CODE VARCHAR(4) NOT NULL,
    VALUES_HOUR01 NUMERIC NOT NULL,
    VALUES_HOUR02 NUMERIC NOT NULL,
    VALUES_HOUR03 NUMERIC NOT NULL,
    VALUES_HOUR04 NUMERIC NOT NULL,
    VALUES_HOUR05 NUMERIC NOT NULL,
    VALUES_HOUR06 NUMERIC NOT NULL,
    VALUES_HOUR07 NUMERIC NOT NULL,
    VALUES_HOUR08 NUMERIC NOT NULL,
    VALUES_HOUR09 NUMERIC NOT NULL,
    VALUES_HOUR10 NUMERIC NOT NULL,
    VALUES_HOUR11 NUMERIC NOT NULL,
    VALUES_HOUR12 NUMERIC NOT NULL,
    VALUES_HOUR13 NUMERIC NOT NULL,
    VALUES_HOUR14 NUMERIC NOT NULL,
    VALUES_HOUR15 NUMERIC NOT NULL,
    VALUES_HOUR16 NUMERIC NOT NULL,
    VALUES_HOUR17 NUMERIC NOT NULL,
    VALUES_HOUR18 NUMERIC NOT NULL,
    VALUES_HOUR19 NUMERIC NOT NULL,
    VALUES_HOUR20 NUMERIC NOT NULL,
    VALUES_HOUR21 NUMERIC NOT NULL,
    VALUES_HOUR22 NUMERIC NOT NULL,
    VALUES_HOUR23 NUMERIC NOT NULL,
    VALUES_HOUR24 NUMERIC NOT NULL
);

-- OFERTA Y GENERACIÓN

-- Disponibilidad declarada

CREATE TABLE xm.DISPONIBILIDAD_DECLARADA (
    FECHA DATE NOT NULL,
    VALUES_CODE VARCHAR(4) NOT NULL,
    VALUES_HOUR01 NUMERIC NOT NULL,
    VALUES_HOUR02 NUMERIC NOT NULL,
    VALUES_HOUR03 NUMERIC NOT NULL,
    VALUES_HOUR04 NUMERIC NOT NULL,
    VALUES_HOUR05 NUMERIC NOT NULL,
    VALUES_HOUR06 NUMERIC NOT NULL,
    VALUES_HOUR07 NUMERIC NOT NULL,
    VALUES_HOUR08 NUMERIC NOT NULL,
    VALUES_HOUR09 NUMERIC NOT NULL,
    VALUES_HOUR10 NUMERIC NOT NULL,
    VALUES_HOUR11 NUMERIC NOT NULL,
    VALUES_HOUR12 NUMERIC NOT NULL,
    VALUES_HOUR13 NUMERIC NOT NULL,
    VALUES_HOUR14 NUMERIC NOT NULL,
    VALUES_HOUR15 NUMERIC NOT NULL,
    VALUES_HOUR16 NUMERIC NOT NULL,
    VALUES_HOUR17 NUMERIC NOT NULL,
    VALUES_HOUR18 NUMERIC NOT NULL,
    VALUES_HOUR19 NUMERIC NOT NULL,
    VALUES_HOUR20 NUMERIC NOT NULL,
    VALUES_HOUR21 NUMERIC NOT NULL,
    VALUES_HOUR22 NUMERIC NOT NULL,
    VALUES_HOUR23 NUMERIC NOT NULL,
    VALUES_HOUR24 NUMERIC NOT NULL
);


-- LISTADOS

-- Listado de agentes con atributos

CREATE TABLE xm.LISTADO_AGENTES_ATRIBUTOS (
    FECHA DATE NOT NULL,
    VALUES_CODE VARCHAR(4) NOT NULL,
    VALUES_NAME VARCHAR(100) NOT NULL,
    VALUES_ACTIVITY VARCHAR(50) NOT NULL,
    VALUES_OPERSTARTDATE DATE NOT NULL,
    VALUES_STATE VARCHAR(20) NOT NULL
);